### ISSUE TITLE
!GetTeam Command

### ISSUE THREAD

**Issue by MarrenDartin** [infamy-organization/infamy_bot#3]
This command will use ANOTHER discord user's discordID to return their current infamy score & placement on the leaderboard based on a user-provided tournament ID.

Example Format:
Tournament Id: 39
Game: valorant
Discord User: LegenDarren
Placement: 1/100

--------------------------------------------
Pro Player Name --- Infamy Score --- In/Out
--------------------------------------------
benjyfishy --- 832 --- Out
leaf --- 152 --- Out
boaster --- 79.5 --- Out
wo0t --- 986.5 --- Out
derke --- 588 --- Out
--------------------------------------------

**Comment by Hemephelus** [comment]
Done.
