### ISSUE TITLE
!myTeam Command

### ISSUE THREAD

**Issue by MarrenDartin** [infamy-organization/infamy_bot#4]
Returns a user team based on tournamentID.

Example Format:
Users DiscordUsername:
Pro Player 1: Infamy Score: In/Out
Pro Player 2: Infamy Score: In/Out
Pro Player 3: Infamy Score: In/Out
Pro Player 4: Infamy Score: In/Out
Captain: Infamy Score: In/Out

(In/Out is if the player is still playing within that tournament)

**Comment by Hemephelus** [comment]
Done
