### ISSUE TITLE
Show earnable Notoriety amount in the tournament listing - High Priority

### ISSUE THREAD

**Issue by MarrenDartin** [infamy-organization/infamy_bot#9]
![image](https://github.com/user-attachments/assets/ec637fe1-65f7-4d3e-a8c9-b185ec720b20)

**Comment by MarrenDartin** [comment]
We want to show some representation of earnable notoriety in the tournament listing after regional can you add either the notoriety values 5, 10, 20, 35 & 50 or maybe a star system of 1-5 stars representing the level of notoriety of each tournament? We would have to add a tooltip explaining the values if we go the star route.

**Comment by Hemephelus** [comment]
I would a bit more clarity on this one.
